chore: fix scripts command
should be pnpm and not npm

I got error when running some tasks
UsageError: This project is configured to use pnpm because package.json has a "packageManager" field

fixes https://github.com/podman-desktop/podman-desktop/issues/10884

Signed-off-by: Florent Benoit <fbenoit@redhat.com>